### ISSUE TITLE
Migrate to teloxide 0.13.0

### ISSUE THREAD

**Issue by LasterAlex** [LasterAlex/teloxide_tests#8]
Teloxide made a lot of changes to the core of the library, to migrate will require some time
The version will probably be 0.2.0, as there will be some breaking changes

I will most definitely do it as soon as i have some free time! 7.0 TBA support is awesome

**Comment by LasterAlex** [comment]
Blocked until teloxide-core release of [this pr](https://github.com/teloxide/teloxide/pull/1145) (it is merged, but not released yet)
Because of that phrase_bot example fails (non-inline keyboard deserialization got broken)
If the releasing takes too long - i will make some form of a crutch with manual deserialization

**Comment by ccbond** [comment]
Expectation

**Comment by LasterAlex** [comment]
@ccbond what?
